R"(
CREATE TRIGGER IF NOT EXISTS XREF BEFORE DELETE ON CONCORDANCE FOR EACH ROW
  BEGIN
    UPDATE FSFILES_CACHED SET PARENTID =
      (SELECT PARENTID FROM FSPARENTS_CACHED WHERE PARENT = OLD.PARENT)
        WHERE FSFILES_CACHED.FILEID = OLD.FILEID;
  END
)"
