R"(
CREATE TABLE IF NOT EXISTS FSFILES_CACHED (
  FILEID INTEGER PRIMARY KEY,
  PARENTID INTEGER,
  STEM TEXT,
  EXTENSION TEXT,
  FOREIGN KEY (PARENTID) REFERENCES FSPARENTS_CACHED(PARENTID)
    DEFERRABLE INITIALLY DEFERRED,
  UNIQUE(PARENTID, STEM, EXTENSION)
)
)"
