R"(
CREATE TABLE IF NOT EXISTS FSSTATS_CACHED (
  FILEID INTEGER,
  FILESIZE INTEGER,
  MODDATE TEXT,
  FILETYPE TEXT,
  MIMETYPE TEXT,
  PERMISSIONS INTEGER,
  FOREIGN KEY (FILEID) REFERENCES FSFILES_CACHED (FILEID)
    ON UPDATE CASCADE ON DELETE CASCADE
)
)"
